/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Account = IDL.Record({
  'dob' : IDL.Text,
  'password' : IDL.Text,
  'phone' : IDL.Text,
  'lastName' : IDL.Text,
  'firstName' : IDL.Text,
});
export const Birthday = IDL.Record({ 'date' : IDL.Text, 'name' : IDL.Text });
export const ImportantMessage = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'author' : IDL.Text,
  'dismissed' : IDL.Bool,
});
export const MeetLink = IDL.Record({ 'url' : IDL.Text, 'title' : IDL.Text });
export const Time = IDL.Int;
export const Message = IDL.Record({
  'content' : IDL.Text,
  'sender' : IDL.Text,
  'timestamp' : Time,
});
export const Photo = IDL.Vec(IDL.Nat8);
export const StarOfTheMonth = IDL.Record({
  'month' : IDL.Text,
  'name' : IDL.Text,
  'position' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'phone' : IDL.Text,
  'lastName' : IDL.Text,
  'firstName' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addImportantMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addOrUpdateBirthday' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addOrUpdateMeetLink' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addOrUpdateStar' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteBirthday' : IDL.Func([IDL.Text], [], []),
  'deleteMeetLink' : IDL.Func([IDL.Text], [], []),
  'deletePhoto' : IDL.Func([IDL.Nat], [], []),
  'deleteStar' : IDL.Func([IDL.Text], [], []),
  'dismissImportantMessage' : IDL.Func([IDL.Nat], [], []),
  'generateOTP' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'getAccount' : IDL.Func([IDL.Text], [Account], ['query']),
  'getAllAccounts' : IDL.Func([], [IDL.Vec(Account)], ['query']),
  'getAllBirthdays' : IDL.Func([], [IDL.Vec(Birthday)], ['query']),
  'getAllImportantMessages' : IDL.Func(
      [],
      [IDL.Vec(ImportantMessage)],
      ['query'],
    ),
  'getAllMeetLinks' : IDL.Func([], [IDL.Vec(MeetLink)], ['query']),
  'getAllMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getAllPhotos' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, Photo))],
      ['query'],
    ),
  'getAllStars' : IDL.Func([], [IDL.Vec(StarOfTheMonth)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPhoto' : IDL.Func([IDL.Nat], [IDL.Opt(Photo)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerAccount' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateAccount' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateImportantMessage' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  'uploadPhoto' : IDL.Func([ExternalBlob], [IDL.Nat], []),
  'verifyOTP' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Account = IDL.Record({
    'dob' : IDL.Text,
    'password' : IDL.Text,
    'phone' : IDL.Text,
    'lastName' : IDL.Text,
    'firstName' : IDL.Text,
  });
  const Birthday = IDL.Record({ 'date' : IDL.Text, 'name' : IDL.Text });
  const ImportantMessage = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'author' : IDL.Text,
    'dismissed' : IDL.Bool,
  });
  const MeetLink = IDL.Record({ 'url' : IDL.Text, 'title' : IDL.Text });
  const Time = IDL.Int;
  const Message = IDL.Record({
    'content' : IDL.Text,
    'sender' : IDL.Text,
    'timestamp' : Time,
  });
  const Photo = IDL.Vec(IDL.Nat8);
  const StarOfTheMonth = IDL.Record({
    'month' : IDL.Text,
    'name' : IDL.Text,
    'position' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'phone' : IDL.Text,
    'lastName' : IDL.Text,
    'firstName' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addImportantMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addOrUpdateBirthday' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addOrUpdateMeetLink' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addOrUpdateStar' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteBirthday' : IDL.Func([IDL.Text], [], []),
    'deleteMeetLink' : IDL.Func([IDL.Text], [], []),
    'deletePhoto' : IDL.Func([IDL.Nat], [], []),
    'deleteStar' : IDL.Func([IDL.Text], [], []),
    'dismissImportantMessage' : IDL.Func([IDL.Nat], [], []),
    'generateOTP' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'getAccount' : IDL.Func([IDL.Text], [Account], ['query']),
    'getAllAccounts' : IDL.Func([], [IDL.Vec(Account)], ['query']),
    'getAllBirthdays' : IDL.Func([], [IDL.Vec(Birthday)], ['query']),
    'getAllImportantMessages' : IDL.Func(
        [],
        [IDL.Vec(ImportantMessage)],
        ['query'],
      ),
    'getAllMeetLinks' : IDL.Func([], [IDL.Vec(MeetLink)], ['query']),
    'getAllMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getAllPhotos' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, Photo))],
        ['query'],
      ),
    'getAllStars' : IDL.Func([], [IDL.Vec(StarOfTheMonth)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPhoto' : IDL.Func([IDL.Nat], [IDL.Opt(Photo)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerAccount' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateAccount' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateImportantMessage' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
    'uploadPhoto' : IDL.Func([ExternalBlob], [IDL.Nat], []),
    'verifyOTP' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };