/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Account {
  'dob' : string,
  'password' : string,
  'phone' : string,
  'lastName' : string,
  'firstName' : string,
}
export interface Birthday { 'date' : string, 'name' : string }
export type ExternalBlob = Uint8Array;
export interface ImportantMessage {
  'id' : bigint,
  'content' : string,
  'author' : string,
  'dismissed' : boolean,
}
export interface MeetLink { 'url' : string, 'title' : string }
export interface Message {
  'content' : string,
  'sender' : string,
  'timestamp' : Time,
}
export type Photo = Uint8Array;
export interface StarOfTheMonth {
  'month' : string,
  'name' : string,
  'position' : string,
}
export type Time = bigint;
export interface UserProfile {
  'phone' : string,
  'lastName' : string,
  'firstName' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addImportantMessage' : ActorMethod<[string, string], undefined>,
  'addOrUpdateBirthday' : ActorMethod<[string, string], undefined>,
  'addOrUpdateMeetLink' : ActorMethod<[string, string], undefined>,
  'addOrUpdateStar' : ActorMethod<[string, string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteBirthday' : ActorMethod<[string], undefined>,
  'deleteMeetLink' : ActorMethod<[string], undefined>,
  'deletePhoto' : ActorMethod<[bigint], undefined>,
  'deleteStar' : ActorMethod<[string], undefined>,
  'dismissImportantMessage' : ActorMethod<[bigint], undefined>,
  'generateOTP' : ActorMethod<[string], bigint>,
  'getAccount' : ActorMethod<[string], Account>,
  'getAllAccounts' : ActorMethod<[], Array<Account>>,
  'getAllBirthdays' : ActorMethod<[], Array<Birthday>>,
  'getAllImportantMessages' : ActorMethod<[], Array<ImportantMessage>>,
  'getAllMeetLinks' : ActorMethod<[], Array<MeetLink>>,
  'getAllMessages' : ActorMethod<[], Array<Message>>,
  'getAllPhotos' : ActorMethod<[], Array<[bigint, Photo]>>,
  'getAllStars' : ActorMethod<[], Array<StarOfTheMonth>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPhoto' : ActorMethod<[bigint], [] | [Photo]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerAccount' : ActorMethod<
    [string, string, string, string, string],
    undefined
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMessage' : ActorMethod<[string, string], undefined>,
  'updateAccount' : ActorMethod<
    [string, string, string, string, string],
    undefined
  >,
  'updateImportantMessage' : ActorMethod<[bigint, string, string], undefined>,
  'uploadPhoto' : ActorMethod<[ExternalBlob], bigint>,
  'verifyOTP' : ActorMethod<[string, bigint], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];